import type { Book } from './types'

/**
 * Demo catalogue — shown in the library when the database has no books yet,
 * so the experience always looks alive. Replace by adding real books in /admin.
 * drive_file_id is empty (books open a "bientôt disponible" notice until real IDs are set).
 */
export const DEMO_BOOKS: Book[] = [
  { id: 'd1',  title: 'La Bible de Jérusalem',                author: 'École Biblique de Jérusalem', category: 'bible',        is_featured: true,  drive_file_id: '', cover_url: null, language: 'fr', year: null, pages: null, description: 'La traduction française de référence, fruit du travail de l\'École biblique.', created_at: '2026-05-20' },
  { id: 'd2',  title: 'Catéchisme de l\'Église Catholique',   author: 'Saint Jean-Paul II',          category: 'catechisme',   is_featured: true,  drive_file_id: '', cover_url: null, language: 'fr', year: null, pages: null, description: 'L\'exposé de référence de la foi catholique.', created_at: '2026-05-19' },
  { id: 'd3',  title: 'Introduction à la Vie Dévote',         author: 'Saint François de Sales',     category: 'spiritualite', is_featured: true,  drive_file_id: '', cover_url: null, language: 'fr', year: null, pages: null, description: 'Un guide intemporel vers la sainteté au quotidien.', created_at: '2026-05-18' },
  { id: 'd4',  title: 'L\'Imitation de Jésus-Christ',         author: 'Thomas a Kempis',             category: 'spiritualite', is_featured: true,  drive_file_id: '', cover_url: null, language: 'fr', year: null, pages: null, description: 'Le classique le plus lu de la spiritualité chrétienne.', created_at: '2026-05-17' },
  { id: 'd5',  title: 'Les Confessions',                      author: 'Saint Augustin',             category: 'theologie',    is_featured: true,  drive_file_id: '', cover_url: null, language: 'fr', year: null, pages: null, description: 'L\'itinéraire spirituel du grand docteur de l\'Église.', created_at: '2026-05-16' },
  { id: 'd6',  title: 'Histoire d\'une Âme',                  author: 'Sainte Thérèse de Lisieux',   category: 'saints',       is_featured: true,  drive_file_id: '', cover_url: null, language: 'fr', year: null, pages: null, description: 'L\'autobiographie de la petite voie de l\'enfance spirituelle.', created_at: '2026-05-15' },
  { id: 'd7',  title: 'Le Château Intérieur',                author: 'Sainte Thérèse d\'Avila',     category: 'spiritualite', is_featured: false, drive_file_id: '', cover_url: null, language: 'fr', year: null, pages: null, description: 'Un chef-d\'œuvre de la mystique carmélitaine.', created_at: '2026-05-14' },
  { id: 'd8',  title: 'Somme Théologique',                    author: 'Saint Thomas d\'Aquin',       category: 'theologie',    is_featured: false, drive_file_id: '', cover_url: null, language: 'fr', year: null, pages: null, description: 'La synthèse magistrale de la théologie scolastique.', created_at: '2026-05-13' },
  { id: 'd9',  title: 'Le Combat Spirituel',                  author: 'Lorenzo Scupoli',            category: 'spiritualite', is_featured: false, drive_file_id: '', cover_url: null, language: 'fr', year: null, pages: null, description: 'Un manuel classique de la vie intérieure.', created_at: '2026-05-12' },
  { id: 'd10', title: 'Vie des Saints',                       author: 'Jacques de Voragine',        category: 'saints',       is_featured: false, drive_file_id: '', cover_url: null, language: 'fr', year: null, pages: null, description: 'La Légende dorée : récits des grands témoins de la foi.', created_at: '2026-05-11' },
  { id: 'd11', title: 'Le Secret du Rosaire',                 author: 'Saint Louis-Marie Grignion', category: 'priere',       is_featured: false, drive_file_id: '', cover_url: null, language: 'fr', year: null, pages: null, description: 'Pour redécouvrir la prière mariale par excellence.', created_at: '2026-05-10' },
  { id: 'd12', title: 'Lumen Gentium',                        author: 'Concile Vatican II',         category: 'papes',        is_featured: false, drive_file_id: '', cover_url: null, language: 'fr', year: null, pages: null, description: 'La constitution dogmatique sur l\'Église.', created_at: '2026-05-09' },
  { id: 'd13', title: 'Traité de l\'Amour de Dieu',          author: 'Saint François de Sales',     category: 'spiritualite', is_featured: false, drive_file_id: '', cover_url: null, language: 'fr', year: null, pages: null, description: 'Une somme sur la charité et la vie en Dieu.', created_at: '2026-05-08' },
  { id: 'd14', title: 'Le Sacrement du Moment Présent',      author: 'Jean-Pierre de Caussade',     category: 'spiritualite', is_featured: false, drive_file_id: '', cover_url: null, language: 'fr', year: null, pages: null, description: 'L\'abandon à la divine Providence.', created_at: '2026-05-07' },
  { id: 'd15', title: 'Missel Romain',                        author: 'Église Catholique',          category: 'liturgie',     is_featured: false, drive_file_id: '', cover_url: null, language: 'fr', year: null, pages: null, description: 'Le livre de la célébration de la messe.', created_at: '2026-05-06' },
  { id: 'd16', title: 'Catéchisme pour les Jeunes (YouCat)',  author: 'Conférence épiscopale',       category: 'jeunesse',     is_featured: false, drive_file_id: '', cover_url: null, language: 'fr', year: null, pages: null, description: 'La foi catholique présentée aux jeunes.', created_at: '2026-05-05' },
]
